version: '3.7'

services:
  backend-server:
    build: ./images/python
    container_name: monogen_server
    restart: always
    volumes:
      - ./..:/usr/src/app
      - ./../storage/static:/usr/src/app/storage/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - database


  database:
    image: postgres:12
    container_name: monogen_postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"


  nginx:
      build: ./images/nginx
      container_name: monogen_nginx
      restart: on-failure
      ports:
        - "80:80"
      volumes:
        - ./../storage/static:/static
      depends_on:
        - backend-server


  redis:
    restart: always
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend-server


volumes:
  postgres_data:
  redis_data:
