"""
Django settings for monogen project.
Generated by 'django-admin startproject' using Django 4.0.

"""

from pathlib import Path

BASE_DIR    = Path(__file__).resolve().parent.parent
PROJECT_DIR = BASE_DIR.parent
WWW_DIR     = PROJECT_DIR.joinpath('www')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-emf-$$&cy)j4ssvva9xc_b@-e#9y-x_ek4+h+j+$)#8!rwhb85'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    # Django applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party applications integration
    'rest_framework',
    'drf_yasg',

    # Monogen system applications
    'components.common.oauth.apps.OauthConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [WWW_DIR.joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PROJECT_DIR.joinpath('storage', 'database.local.sqlite3'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript)
STATIC_URL = 'static/'
STATICFILES_DIRS = [WWW_DIR.joinpath('static')]

# Media files (Image: .png, .jpg, .jpeg; Docfiles: .docx, .pdf, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.joinpath('www', 'media')


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# JWT
JWT_ALGORITHM = 'HS2256'
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24 # 24 hours

# Google Console
GOOGLE_CLIENT_ID = '749331434728-c0tljunbvtjigajbgh44i609bf8gp26t.apps.googleusercontent.com'
